version: '3.7'

services:
  # MinIO server
  minio:
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z.fips
    hostname: minio
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      # MinIO Console is available at http://localhost:9001
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio_user}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio_password}
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Create a bucket named "bucket" if it doesn't exist
  minio-create-bucket:
    image: minio/mc:RELEASE.2024-07-26T13-08-44Z.fips
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      bash -c "
      mc alias set minio http://minio:9000 minio_user minio_password &&
      mc mb minio/raw --ignore-existing  &&
      mc mb minio/curated --ignore-existing  &&
      mc mb minio/artifacts --ignore-existing  &&
      mc cp --recursive /data/gh_archive minio/raw
      "
    volumes:
      - ./data:/data

volumes:
  minio_data:
